FROM flow123d/endorse_ci:e67f54

COPY requirements.txt /tmp/requirements.txt

# This enables temporary files using mount, instead of removing copy layers
# https://docs.docker.com/build/buildkit/
# RUN --mount=type=bind,source=requirements.txt,target=/tmp/requirements.txt \

RUN python3 -m pip install -U pip && \
    pip3 install -r /tmp/requirements.txt  && \
    rm /tmp/requirements.txt

RUN apt-get install sshpass