FROM flow123d/endorse_ci:a785dd
COPY requirements.txt /root/requirements.txt
COPY sample_script.py /root/sample_script.py
COPY pymc_metropolis.py /root/pymc_metropolis.py
COPY blackbox.py /root/blackbox.py
RUN python3 -m venv ~/.virtualenvs/bruh
RUN source ~/.virtualenvs/bruh/bin/activate
RUN pip install -r /root/requirements.txt
