FROM flow123d/endorse_ci:14a6cb

COPY requirements.txt /tmp/requirements.txt
# COPY sample_script.py /root/sample_script.py
# COPY pymc_metropolis.py /root/pymc_metropolis.py
# COPY blackbox.py /root/blackbox.py

# RUN python3 -m venv ~/.virtualenvs/bruh
# RUN source ~/.virtualenvs/bruh/bin/activate
# RUN pip install -r /root/requirements.txt

# RUN sudo apt-get update && sudo apt-get install -y \
#     <new_package>


# This enables temporary files using mount, instead of removing copy layers
# https://docs.docker.com/build/buildkit/
# RUN --mount=type=bind,source=requirements.txt,target=/tmp/requirements.txt \

RUN python3 -m pip install -U pip && \
    pip3 install -r /tmp/requirements.txt  && \
    rm /tmp/requirements.txt && \
    pip3 install \
        pytest \
        wheel
