flow123d_version: 4.0.0
problem: !Coupling_Sequential
  description: Model of tunnel surroundings relaxation after boring.
  mesh:
    mesh_file: <mesh>
    regions:
      - !Union
        name: .outer_boundary
        regions: [.bottom, .top, .left, .right]
  flow_equation: !Coupling_Iterative
    input_fields:
      - region: BULK
        biot_alpha: <biot_coefficient>
        fluid_density: 1000
    time:
      end_time: <end_time>
      # common time unit cannot be used in field formulas
      common_time_unit: d
    iteration_parameter: 1 # affects convergence of HM coupling (defaults to 1, lower value sometimes helps)
    a_tol: 0
    r_tol: 1e-5
    flow_equation: !Flow_Richards_LMH
        user_fields:
          - name: sx
            field: <init_stress_x>
          - name: sy
            field: <init_stress_y>
          - name: sz
            field: <init_stress_z>
          - name: init_p
            field: !FieldFormula
              value: <init_pressure>-z
          - name: k0
            field: !FieldFormula
              value: <perm_k0>
          - name: kr
            field: !FieldFormula
              value: 1/<perm_eps>*k0
          - name: delta
            field: <perm_delta>
          - name: gamma
            field: <perm_gamma>
          - name: stress_threshold
            field: 55e6
          - name: nonlin_cond
            field: !FieldFormula
              value: 1000*9.81/0.001 * (kr + delta*exp( log((k0-kr)/delta) * mean_stress/(-(sx+sy+sz)/3)))
        nonlinear_solver:
          linear_solver: !Petsc
            a_tol: <flow_solver__a_tol>
            r_tol: <flow_solver__r_tol>
            options: <flow_solver__options>
        input_fields:
          - region: BULK
            conductivity: !FieldFormula
              value:
                ( nonlin_cond if (von_mises_stress<stress_threshold)
                  else nonlin_cond * exp(gamma*(von_mises_stress-stress_threshold)/stress_threshold)
                )

            # https://en.wikipedia.org/wiki/Specific_storage
            storativity: <storativity>
            # S = rho * g * (beta_s + nu * beta_w)
            # 9.81e3 * (3*(1-2*0.23)/60e9 + 0.007*5.1e-10)
            # bulk compressibility beta_s=1/K = (3(1-2pr)/E) 
            # porosity nu=0.007
            # water compressibility beta_w=5.1 1/Pa
            init_pressure: !FieldFormula
              value: init_p

          - region: .outer_boundary
            bc_type: dirichlet
            bc_pressure: !FieldFormula
              value: init_p

          - region: .tunnel
            time: 0
            bc_type: dirichlet
            bc_pressure: !FieldFormula
              value: init_p*(-1/(<bored_time>*86400)*t + 1) # 1d=86400s
          - region: .tunnel
            time: <bored_time>
            bc_type: dirichlet
            bc_pressure: 0

        output:
          times: <output_times>
          fields: []
          # - { field: conductivity, interpolation: P1_average }
          # - piezo_head_p0
          # - pressure_p0
#         #   - velocity_p0
          # - region_id
          observe_fields: [pressure_p0, conductivity]
        #balance:
          #cumulative: true
        output_stream:
          format: !vtk
          observe_points: &observe_points
            - { name: V1, point: [ 0, 3.25, 0 ] }  # HGT1-5: 3.5/2 + 1.5
            - { name: V2, point: [ 0, 5.75, 0 ] }  # HGT1-4: 3.5/2 + 4
            - { name: H1, point: [ 3.6875, 0, 0 ] }  # HGT2-4: 4.375/2 + 1.5
            - { name: H2, point: [ 6.1875, 0, 0 ] }  # HGT2-3: 4.375/2 + 4
            - { name: V1_cond, point: [ 0, 1.75, 0 ] }  # : 3.5/2
            - { name: V2_cond, point: [ 0, 2.15, 0 ] }  # : 3.5/2 + 0.4
            - { name: H1_cond, point: [ 2.1875, 0, 0 ] }  # : 4.375/2
            - { name: H2_cond, point: [ 2.7875, 0, 0 ] }  # : 4.375/2 + 0.6
    mechanics_equation:
        user_fields:
          - name: sx # initial stress in x direction (orthogonal to tunnel axis)
            field: <init_stress_x>
          - name: sy
            field: <init_stress_y>
          - name: sz
            field: <init_stress_z>
        output_stream:
          format: !vtk
#          observe_points: *observe_points
        output:
          times: <output_times>
          fields: []
            #- { field: displacement, interpolation: P1_average }
            #- stress
#           # - displacement_divergence
            #- mean_stress
            #- von_mises_stress
            #- initial_stress
            #- region_id
          observe_fields: [von_mises_stress]
        solver: !Petsc
          a_tol: <mechanics_solver__a_tol>
          r_tol: <mechanics_solver__r_tol>
          options: <mechanics_solver__options>
        input_fields:
          - region: BULK
            young_modulus: <young_modulus>
            poisson_ratio: <poisson_ratio>
            initial_stress: !FieldFormula
              value: "[[-sx, 0, 0], [0, -sy, 0], [0, 0, -sz]]"

          - region: .outer_boundary
            bc_type: displacement
            bc_displacement: 0

          # bc_type stress prepocita tenzor napeti na normalovou silu, s normalou orientovanou dovnitr
          # bc_stress * vnitřní normála = bc_traction = síla působící na těleso
          - region: .tunnel
            time: 0
            bc_type: stress
            bc_stress: !FieldFormula
              value: "[[-sx, 0, 0],
                       [0, -sy, 0],
                       [0, 0, -sz]]*(1/(<bored_time>*86400)*t)" # 1d=86400s
          - region: .tunnel
            time: <bored_time>
            bc_type: stress
            bc_stress: !FieldFormula
              value: "[[-sx, 0, 0], [0, -sy, 0], [0, 0, -sz]]"
